### ISSUE TITLE
Memory leak detection test

### ISSUE THREAD

**Issue by mmartinm** [01org/cc-oci-runtime#412] opened 2016-11-16 20:57 UTC
Scenario 1
Create multiple Containers then  start and stop  them in a loop and 
1 ) measure memory before containers start
2 ) while containers are running and 
3 ) after containers stopped.

Scenario 2 
Create and Delete multiple Containers in a loop and 
1) measure memory before containers creation
2)  while containers are running and 
3) after containers destruction.

**Comment by dlespiau** [comment] 2016-11-17 17:21
That seems like odd things to be doing.

We can have leaks but we also have a lot of short lived processes (the runtime doesn't stay around) so all the memory used by those short-lived processes is freed.

`cc-shim` is potentially a long running process (as long as the container itself) so it'd be nice to monitor that one. You can't quite do that with master though, that's 2.1 work.

In short, not totally convinced of the value of this.

**Comment by mcastelino** [comment] 2016-11-18 22:27
@dlespiau this is beyond memory leak detection. If we leak any resources including files, volumes or any other resources which are not reclaimed on qemu process termination etc this test will catch this. We have seen failure of this test after 27,770 container launch and teardowns. This may be a issues with docker itself or cc-oci-runtime.

So there is value in this test.

**Comment by dlespiau** [comment] 2016-11-19 00:34
If it's not only about memory, then it shouldn't be called "Memory leak detection test" and only talk about memory :)

**Comment by grahamwhaley** [comment] 2016-11-22 14:42
I suspect this is resource leak detection by memory leak detection - so not quite a clear cut case yet - so, yes, let's keep an eye on this and ensure the ticket description is accurate for the work we are doing :-)

**Comment by dborquez** [comment] 2016-11-29 16:29
Container cannot exit and test hangs in iteration close to 3000 out of 64K.

**Comment by dlespiau** [comment] 2016-11-29 16:48
Is that using the master branch? or the 2.1 branch?

**Comment by dborquez** [comment] 2017-02-01 17:08
This issue is caused by fd leaks as such described in #616, closing.

**Closed by dborquez** 2017-02-01 17:08 UTC
Labels: functional testing
