### ISSUE TITLE
"docker run hello-world" fails

### ISSUE THREAD

**Issue by rbradford** [01org/cc-oci-runtime#222] opened 2016-09-06 17:57 UTC
rob@hercules:~/src/cc-oci-runtime$ sudo docker run --runtime=cor -ti hello-world
container-workload.service: Failed at step EXEC spawning /.containerexec: No such file or directory

rob@hercules:~/src/cc-oci-runtime$ sudo docker run --runtime=cor hello-world
container-workload.service: Failed at step EXEC spawning /.containerexec: No such file or directory

**Comment by grahamwhaley** [comment] 2016-09-06 18:12
Hello @rbradford , welcome.
Is hello-world a 'standard' docker image - maybe something from the Docker hub?
Given your work dir, I presume you built the cor runtime from source - we can also try this from the package/bundle install to narrow down/eliminate differences.

**Comment by rbradford** [comment] 2016-09-06 18:21
Hi @grahamwhaley - "hello-world" is the test image used as part of the docker installation guide to help you test that you have docker configured correctly. It is intentionally very minimal. 

Other images run fine, e.g. the ubuntu image.

**Comment by grahamwhaley** [comment] 2016-09-06 19:07
Ah, thanks. I suspect it is so minimal that it will not execute our 'secret' file '.containerexec'.
If I run 'docker run -it busybox', I can see that file, and if I cat it, it has the contents:

```
  #!/bin/bash
  cd '/'
  'sh'
```

This is used by the 'mini-OS' VM kernel/rootfs to run the workload. I think we're going to have to see just how minimal 'hello-world' really is.

**Comment by grahamwhaley** [comment] 2016-09-06 19:18
Heh, so I think you have chosen what is effectively our 'hardest test' for our launcher. afaict, the layer in 'hello-world' containers precisely one file, and that is the executable 'hello', that prints the message you were hoping to see.
This is an interesting issue I think we should at least discuss a little more for a good technical understanding. I'm now wondering if the problem is that the image does not have a shell, or maybe a homedir. @jodh-intel , what do you think - any immediate ideas. I'd at least like to understand why it does not work, and thus sort of define a 'current minimum requirements' for what an image must have to be runnable by the runtime.

**Comment by jodh-intel** [comment] 2016-09-07 15:52
@grahamwhaley - I think we're going to have to consider including something like a static version of `busybox`/`toybox` in the mini-os that can be made available in the chroot so that we don't require the docker image to contain a shell. However, those tools don't provide a full `bash`, so this might not be sufficient.

**Comment by grahamwhaley** [comment] 2016-09-07 16:06
Yeah, I'm going to have to understand more of what can be done pre-chroot and what has to be done in the chroot to comprehend that. We need to do the minimum necessary in the chroot obviously, so we should probably define what that is by defining the functionality that has to be supported.
This should probably come along with part of the potential 2.1 agent etc. restructure I think.

**Comment by jodh-intel** [comment] 2016-09-07 16:22
As a mimimum, we should probably dispense with `/.containerexec` if there is no shell available. But that decision will need to be made at runtime in something like `container-workload.service`.

**Comment by jodh-intel** [comment] 2016-09-08 15:53
This is related to #226 - we need to test with the top / most popular docker hub images.

**Comment by GabyCT** [comment] 2016-10-13 22:10
The same error is in the traefik image
 docker run -ti traefik traefik --version
container-workload.service: Failed at step EXEC spawning /.containerexec: No such file or directory

**Comment by GabyCT** [comment] 2016-12-02 21:06
I tested it using CC 2.1 and it is working
 # docker run --rm -i hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

**Comment by grahamwhaley** [comment] 2016-12-20 11:24
So, @GabyCT - we can close this one now? I think so...

**Comment by jcvenegas** [comment] 2016-12-27 21:38
2.1 is merged in master

**Closed by jcvenegas** 2016-12-27 21:38 UTC
Labels: P1, type:bug
