### ISSUE TITLE
proxy tests are still racy

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#384] opened 2016-11-10 12:05 UTC
```
while [ $i -lt 100 ]
do
    make check-proxy
    if [ $? -ne 0 ]
    then
        echo "ERROR: failed on iteration $i"
        break
    fi
    i=$((i+1))
done
```

I just got this output:

```
    :
[hyperstart] stopped
--- PASS: TestAllocateIo (0.01s)
PASS
Found 1 data race(s)
exit status 66
FAIL    _/home/james/git/cc-oci-runtime/proxy   1.041s
Makefile:4917 : la recette pour la cible « check-proxy » a échouée
make: *** [check-proxy] Erreur 1
ERROR: failed on iteration 18
```

It appears that this is causing PR #383 to fail under Travis.

**Comment by dlespiau** [comment] 2016-11-11 08:47
Of course, I can't reproduce it locally. One trace I found in travis seems to be in the waitgroup itself, which is quite unexpected.

```
==================
WARNING: DATA RACE
Write at 0x00c4200102b4 by goroutine 21:
  internal/race.Write()
      /home/travis/go/src/internal/race/race.go:41 +0x38
  sync.(*WaitGroup).Wait()
      /home/travis/go/src/sync/waitgroup.go:129 +0x151
  github.com/01org/cc-oci-runtime/tests/mock.(*Hyperstart).Stop()
      /home/travis/gopath/src/github.com/01org/cc-oci-runtime/tests/mock/hyperstart.go:380 +0xfe
  _/home/travis/build/chavafg/cc-oci-runtime/cc-oci-runtime-0.1/proxy.(*testRig).Stop()
      /home/travis/build/chavafg/cc-oci-runtime/cc-oci-runtime-0.1/proxy/proxy_test.go:170 +0xd8
  _/home/travis/build/chavafg/cc-oci-runtime/cc-oci-runtime-0.1/proxy.TestBye()
      /home/travis/build/chavafg/cc-oci-runtime/cc-oci-runtime-0.1/proxy/proxy_test.go:241 +0x7df
  testing.tRunner()
      /home/travis/go/src/testing/testing.go:610 +0xc9
Previous read at 0x00c4200102b4 by goroutine 22:
  internal/race.Read()
      /home/travis/go/src/internal/race/race.go:37 +0x38
  sync.(*WaitGroup).Add()
      /home/travis/go/src/sync/waitgroup.go:71 +0x292
  github.com/01org/cc-oci-runtime/tests/mock.(*Hyperstart).Start.func1()
      /home/travis/gopath/src/github.com/01org/cc-oci-runtime/tests/mock/hyperstart.go:359 +0xa1
  github.com/01org/cc-oci-runtime/tests/mock.(*Hyperstart).startListening.func1()
      /home/travis/gopath/src/github.com/01org/cc-oci-runtime/tests/mock/hyperstart.go:335 +0x177
```

**Comment by dlespiau** [comment] 2016-11-11 08:51
As I can't reproduce it, It'd be nice if you could provide your race/strack trace in case of a sigsegv as well in case there are different.

**Comment by dlespiau** [comment] 2016-11-11 09:44
Another trace (roughly same place, that's definitely the weak part that may need a bit of redesign):

```
==================
WARNING: DATA RACE
Read at 0x00c420010308 by goroutine 20:
  github.com/01org/cc-oci-runtime/tests/mock.(*Hyperstart).readCtl()
      /home/travis/gopath/src/github.com/01org/cc-oci-runtime/tests/mock/hyperstart.go:133 +0x6b
  github.com/01org/cc-oci-runtime/tests/mock.(*Hyperstart).readMessage()
      /home/travis/gopath/src/github.com/01org/cc-oci-runtime/tests/mock/hyperstart.go:150 +0xa2
  github.com/01org/cc-oci-runtime/tests/mock.(*Hyperstart).handleCtl()
      /home/travis/gopath/src/github.com/01org/cc-oci-runtime/tests/mock/hyperstart.go:225 +0x6e
Previous write at 0x00c420010308 by goroutine 14:
  github.com/01org/cc-oci-runtime/tests/mock.(*Hyperstart).Stop()
      /home/travis/gopath/src/github.com/01org/cc-oci-runtime/tests/mock/hyperstart.go:382 +0x10c
  _/home/travis/build/01org/cc-oci-runtime/cc-oci-runtime-0.1/proxy.(*testRig).Stop()
      /home/travis/build/01org/cc-oci-runtime/cc-oci-runtime-0.1/proxy/proxy_test.go:170 +0xd8
  _/home/travis/build/01org/cc-oci-runtime/cc-oci-runtime-0.1/proxy.TestHello()
      /home/travis/build/01org/cc-oci-runtime/cc-oci-runtime-0.1/proxy/proxy_test.go:206 +0x803
  testing.tRunner()
      /home/travis/go/src/testing/testing.go:610 +0xc9
  _/home/travis/build/01org/cc-oci-runtime/cc-oci-runtime-0.1/proxy.(*testRig).Stop()
      /home/travis/build/01org/cc-oci-runtime/cc-oci-runtime-0.1/proxy/proxy_test.go:170 +0xd8
  _/home/travis/build/01org/cc-oci-runtime/cc-oci-runtime-0.1/proxy.TestHello()
      /home/travis/build/01org/cc-oci-runtime/cc-oci-runtime-0.1/proxy/proxy_test.go:206 +0x803
  testing.tRunner()
      /home/travis/go/src/testing/testing.go:610 +0xc9
```

**Comment by dlespiau** [comment] 2016-11-11 10:21
Oh I found the sentence documenting the Waitgroup race we're seeing: "Note that calls with a positive delta that occur when the counter is zero must happen before a Wait" (https://golang.org/pkg/sync/#WaitGroup.Wait). I thought calling Wait before Add(1) would be just fine.

**Comment by dlespiau** [comment] 2016-11-12 13:12
Now fixed!

**Closed by dlespiau** 2016-11-12 13:12 UTC
Labels: domain:tests, P1, type:bug
