### ISSUE TITLE
containerd error in docker logs: ERRO[69610] failed to close stdin: rpc error: code = 2 desc = containerd: process not found for container 

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#646] opened 2017-02-03 12:55 UTC
There's something we don't do "correctly" still when spawning the shim. To reproduce:

- I'm using docker 1.12.5 (can probably be reproduced elsewhere)
- running the full docker integration test suite shows quite a few of those in the docker logs

edit: oh, actually I was running docker 1.12.5 for this one.

**Comment by devimc** [comment] 2017-02-17 18:50
checking 1.12.1 ...

**Comment by devimc** [comment] 2017-02-23 22:38
Cannot reproduce using docker 1.12.1
@dlespiau  can we close it?

**Comment by chavafg** [comment] 2017-02-28 21:55
Haven't hit this error again, I think we can close it.

**Comment by devimc** [comment] 2017-02-28 21:56
closing issue

thanks @chavafg

**Closed by devimc** 2017-02-28 21:56 UTC
