### ISSUE TITLE
Enable 'make check' within Travis

### ISSUE THREAD

**Issue by grahamwhaley** [01org/cc-oci-runtime#69] opened 2016-08-04 10:39 UTC
Travis is now doing a build check, but we can enhance that to add a run check with 'make check'.

**Comment by dlespiau** [comment] 2016-08-10 15:05
#PR 109 is step towards that and runs make check in travis.

However the following things still need consideration:

- The valgrind tests aren't run for some reason

- It doesn't seem possible to use KVM within travis (googled around and asked @sameo that has ran into the same issue with ciao). However, we might be happy enough with launching qemu without KVM support, as we're really only testing our interfaces, not KVM itself (or so I believe). In that case we'd need to:
    - compile qemu-lite
    - fetch a clear image and container kernel
    - prepare an OCI bundle in tests/functional/bundle
    - make check should then run the functional tests

**Comment by jodh-intel** [comment] 2016-09-27 08:03
This seems like a duplicate of #255 where I investigated running the full test suite under Travis. In summary, we don't think this is possible given the lack of VT-x support in the Travis environment.

Valgrind *is* configured to run, but valgrind's `helgrind` and `drd` tools are explicitly disabled. For an explanation see commit 614fb442cba6102f6de7ca44dd02725c7ebca083. However, there seems to be a
problem running valgrind under Travis (see issue #295).

**Comment by dlespiau** [comment] 2016-09-27 08:37
ok, it seems we have more precise issues describing the remaining problem(s), let's close that one, we do run make check in travis after all.

**Closed by dlespiau** 2016-09-27 08:37 UTC
Labels: domain:tests, domain:travis, P2, ready, Sprint, type:enhancement
