### ISSUE TITLE
Networking - Enable cc-oci-networking support for docker swarm

### ISSUE THREAD

**Issue by mcastelino** [01org/cc-oci-runtime#83] opened 2016-08-05 15:34 UTC
The current networking implementation support bridge networking. 

We need to support at least one overlay network framework. The first overlay network we need to enable is swarm with the current integration bridge approach if possible.

**Comment by grahamwhaley** [comment] 2016-08-08 17:46
Hi @mcastelino - could you note here why this is closed with, afaict, no activity. Has it been replaced by other issue tickets for instance etc.?  Thanks.

**Comment by mcastelino** [comment] 2016-08-08 19:41
Duplicated by https://github.com/01org/cc-oci-runtime/issues/95

**Comment by dlespiau** [comment] 2016-09-05 10:50
Can we close that issue? it seems covered by #95 or it needs to be more specific.

**Comment by dlespiau** [comment] 2016-09-09 11:11
Closing as duplicate of #95 as discussed with @mcastelino offline.

**Closed by dlespiau** 2016-09-09 11:11 UTC
Labels: networking
