### ISSUE TITLE
Telemetry crash related to cc_run_hook()

### ISSUE THREAD

**Issue by sboeuf** [01org/cc-oci-runtime#760] opened 2017-03-21 19:44 UTC
Telemetry crash 774.
Something wrong happened after the runtime forked to do a re-exec of the OCI hook provided.

**Comment by sboeuf** [comment] 2017-03-21 19:45
@devimc I have assigned this to you as you're driving cc-oci-runtime. Feel free to assign it to someone else who could take some time to investigate this.
@dlespiau any ideas what could be the reason for such kind of failure ?

**Comment by jodh-intel** [comment] 2017-03-22 09:14
@sboeuf - Are there any associated logs to help with debugging here (docker, bats, runtime, etc)?

I'm only seeing a summary of the backtrace, which only seems tho show that a crash occurred in `cc_run_hook()`, but not exactly where nor what the inputs were.

**Comment by sboeuf** [comment] 2017-03-22 13:05
@jodh-intel I agree this is really complicated to understand the root cause. I have asked about test setup or extra logs we could use to help us, but apparently there is no such thing. Telemetry seems to report only crashes but we cannot know what was the reason for this...

**Comment by icarus-sparry** [comment] 2017-03-28 19:58
The only obvious call to abort() in the path including cc_run_hooks() is the one in cc_run_hook() (Presumably inlined as it is static and only has one call site).  This will be called if the system fails to execvpe the program given by hook->path.

(Failures to execvpe are usually caused by the program not being on the PATH, but can be due to missing resources. symbolic link loops, I/O errors and so on)

The code does do a call to g_critical to log an error message in the child process. 

I think it would make more sense to just call exit() with the value of errno rather than abort(). The parent already has code to handle the process failing. The core does draw attention to the issue, which is good.

**Comment by amshinde** [comment] 2017-03-28 20:44
There are a few crashes originating from my machine in the telemetry logs. I had changed my telemetry machine-id to a recognizable name a few days back to track any crashes. Comparing the pids in the telemetry logs to the cc-oci-runtime logs, I can say that the issue was with exec-ing the hooks, specifically :
"failed to exec hook /usr/bin/dockerd (deleted): No such file or directory"

This was caused due to missing files during the the container bundle split (containers-basic and containers-virt), causing certain files to not be deleted.

I do agree with @icarus-sparry, it would make sense to exit() with errno rather than calling abort() here.

**Comment by sboeuf** [comment] 2017-03-30 19:26
@sameo @jodh-intel @dlespiau @grahamwhaley What do you think about that ? We can simply get rid of every abort() in the code and replace them with exit(errno) ?

**Comment by jodh-intel** [comment] 2017-04-03 12:49
@sboeuf - yes, I agree. Additional to removing those calls, we should ensure we also call `g_critical()`, passing it `strerror(saved_errno)` before calling `exit(saved_errno)`.

**Comment by jodh-intel** [comment] 2017-04-06 13:34
Closing as problem was fixed.

**Closed by jodh-intel** 2017-04-06 13:34 UTC
