### ISSUE TITLE
failed to run hyper cmd startpod

### ISSUE THREAD

**Issue by jcvenegas** [01org/cc-oci-runtime#623] opened 2017-01-25 20:02 UTC
By time to time docker can not run a container printing the following error:
docker: Error response from daemon: shim error: open pid: no such file or directory

This this seems by en error by when we try to start a pod, cc-proxy return the following error:
```
debug:writing message data to proxy socket: {"id":"hyper","data":{"hyperName":"startpod","data":{"hostname":"f11dd6d39246","containers":[],"shareDir":"rootfs","interfaces":[{"device":"enp0s8","newDeviceName":"eth0","ipAddresses":[{"ipAddress":"172.17.0.2","netMask":"255.255.0.0"}]}],"routes":[{"dest":"default","gateway":"172.17.0.1","device":"eth0"},{"dest":"172.17.0.0","device":"eth0"}]}}}
debug:msg length: 58
debug:message read from proxy socket: {"success":false,"error":"ERROR received from Hyperstart"}
failed to run hyper cmd startpod: {"success":false,"error":"ERROR received from Hyperstart"}
critical:failed to run pod create
```

The issue random, and easy way to reproduce it is : 
```
while docker run --rm -ti debian true ;do  echo running ; done
```
docker info:
```
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: cc cc-debug cor oci runc
Default Runtime: cc-debug
Security Options:
Kernel Version: 4.9.5-402.native
Operating System: Clear Linux Software for Intel Architecture
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.66 GiB
```

cc-proxy log (-v=4):
```
[client #360] hello(containerId=bc01b8e1e7f3791e8e1b84b5d9da110457c6a4889ca7717886d88970da2fd715,ctlSerial=/var/run/cc-oci-runtime/bc01b8e1e7f3791e8e1b84
        [vm bc01b8e1 hyperstart] open hyper channel /dev/vport1p1
        [vm bc01b8e1 hyperstart] send ready message
        [vm bc01b8e1 hyperstart] hyper send type 8, len 0
        [vm bc01b8e1 hyperstart] open hyper channel /dev/vport1p2
[client #360] hyper(cmd=startpod, data={"hostname":"bc01b8e1e7f3","containers":[],"shareDir":"rootfs","interfaces":[{"device":"enp0s8","newDeviceName":"e
        [vm bc01b8e1 hyperstart] hyper_init_event hyper channel event 0x41e1b0, ops 0x41e030, fd 3
        [vm bc01b8e1 hyperstart] hyper_add_event add event fd 3, 0x41e030
        [vm bc01b8e1 hyperstart] hyper_init_event hyper ttyfd event 0x41e178, ops 0x41e010, fd 4
        [vm bc01b8e1 hyperstart] hyper_add_event add event fd 4, 0x41e010
        [vm bc01b8e1 hyperstart] hyper_loop epoll_wait 1
        [vm bc01b8e1 hyperstart] hyper_handle_event get event 1, he 0x41e1b0, fd 3. ops 0x41e030
        [vm bc01b8e1 hyperstart] hyper_handle_event event EPOLLIN, he 0x41e1b0, fd 3, 0x41e030
        [vm bc01b8e1 hyperstart] hyper_channel_read
        [vm bc01b8e1 hyperstart] hyper send type 14, len 4
        [vm bc01b8e1 hyperstart] get length 303
        [vm bc01b8e1 hyperstart] hyper send type 14, len 4
        [vm bc01b8e1 hyperstart] 0 0 0 1 0 0 1 2f 7b 22 68 6f 73 74 6e 61 6d 65 22 3a 22 62 63 30 31 62 38 65 31 65 37 66 33 22 2c 22 63 6f 6e 74 61 69 6e 65 72 73
        [vm bc01b8e1 hyperstart]  hyper_channel_handle, type 1, len 303
        [vm bc01b8e1 hyperstart] call hyper_start_pod, json {"hostname":"bc01b8e1e7f3","containers":[],"shareDir":"rootfs","interfaces":[{"device":"enp0s8","newDev
        [vm bc01b8e1 hyperstart] call hyper_start_pod, json {"hostname":"bc01b8e1e7f3","containers":[],"shareDir":"rootfs","interfaces":[{"device":"enp0s8","newDev
        [vm bc01b8e1 hyperstart] jsmn parse successed, n is 35
        [vm bc01b8e1 hyperstart] token 0, type is 1, size is 5
        [vm bc01b8e1 hyperstart] token 1, type is 3, size is 1
        [vm bc01b8e1 hyperstart] hostname is bc01b8e1e7f3
        [vm bc01b8e1 hyperstart] token 3, type is 3, size is 1
        [vm bc01b8e1 hyperstart] container count 0
        [vm bc01b8e1 hyperstart] token 5, type is 3, size is 1
        [vm bc01b8e1 hyperstart] share tag is rootfs
        [vm bc01b8e1 hyperstart] token 7, type is 3, size is 1
        [vm bc01b8e1 hyperstart] network interfaces num 1
        [vm bc01b8e1 hyperstart] net device is enp0s8
        [vm bc01b8e1 hyperstart] new interface name is eth0
        [vm bc01b8e1 hyperstart] Number of ip addresses:1
        [vm bc01b8e1 hyperstart] net ipaddress for device enp0s8 is 172.17.0.2
        [vm bc01b8e1 hyperstart] net mask for device enp0s8 is 255.255.0.0
        [vm bc01b8e1 hyperstart] token 21, type is 3, size is 1
        [vm bc01b8e1 hyperstart] network routes num 2
        [vm bc01b8e1 hyperstart] route 0 dest is default
        [vm bc01b8e1 hyperstart] route 0 gateway is 172.17.0.1
        [vm bc01b8e1 hyperstart] route 0 device is eth0
        [vm bc01b8e1 hyperstart] route 1 dest is 172.17.0.0
        [vm bc01b8e1 hyperstart] route 1 device is eth0
        [vm bc01b8e1 hyperstart] create directory /tmp/hyper
        [vm bc01b8e1 hyperstart] create directory /tmp/hyper/proc
        [vm bc01b8e1 hyperstart] finish rescan
        [vm bc01b8e1 hyperstart] net device enp0s8
        [vm bc01b8e1 hyperstart] net device sys path is /sys/class/net/enp0s8/ifindex
        [vm bc01b8e1 hyperstart] get ifindex 2
        [vm bc01b8e1 hyperstart] interface get netamsk 16 255.255.0.0
        [vm bc01b8e1 hyperstart] Setting interface name to eth0
        [vm bc01b8e1 hyperstart] hwclock: Cannot access the Hardware Clock via any known method.
        [vm bc01b8e1 hyperstart] hwclock: Use the --debug option to see the details of our search for an access method.
        [vm bc01b8e1 hyperstart] net device eth0
        [vm bc01b8e1 hyperstart] net device sys path is /sys/class/net/eth0/ifindex
        [vm bc01b8e1 hyperstart] get ifindex 2
        [vm bc01b8e1 hyperstart] net device eth0
```
runtime version:
2.1-rc1 to 2.4-rc1

**Comment by chavafg** [comment] 2017-01-25 20:37
Seems like it happens only with docker 1.12.6, when running on fedora and clearlinux with 1.12.5, I got no issues, but when upgrading to 1.12.6, the issue is reproduced easily

**Comment by chavafg** [comment] 2017-01-25 21:07
Nevermind, I just reproduced with 1.12.5 on Ubuntu 16.04

```
not ok 3 Volume - use volume in a container
# (in test file volume.bats, line 46)
#   `[ $status -eq 0 ]' failed
#   2017-01-25T14:52:41.649326Z:24578:cc-oci-runtime:critical:failed to run hyper cmd startpod: {"success":false,"error":"ERROR received from Hyperstart"}

2017-01-25T14:52:41.649393Z:24578:cc-oci-runtime:critical:failed to run pod create

2017-01-25T14:52:41.649741Z:24586:cc-oci-runtime:critical:failed to read proxy socket fd

docker: Error response from daemon: shim error: open pid: no such file or directory.
```

cc-oci-runtime.log 
```
2017-01-25T14:52:41.646101Z:24578:cc-oci-runtime:debug:writing message data to proxy socket: {"id":"hyper","data":{"hyperName":"startpod","data":{"hostname":"a77930e6b7b2","containers":[],"shareDir":"rootfs","interfaces":[{"device":"enp0s
8","newDeviceName":"eth0","ipAddresses":[{"ipAddress":"172.17.0.2","netMask":"255.255.0.0"}]}],"routes":[{"dest":"default","gateway":"172.17.0.1","device":"eth0"},{"dest":"172.17.0.0","device":"eth0"}]}}}
2017-01-25T14:52:41.649137Z:24578:cc-oci-runtime:debug:proxy msg length: 58
2017-01-25T14:52:41.649240Z:24578:cc-oci-runtime:debug:message read from proxy socket: {"success":false,"error":"ERROR received from Hyperstart"}
2017-01-25T14:52:41.649326Z:24578:cc-oci-runtime:critical:failed to run hyper cmd startpod: {"success":false,"error":"ERROR received from Hyperstart"}
2017-01-25T14:52:41.649393Z:24578:cc-oci-runtime:critical:failed to run pod create
2017-01-25T14:52:41.649741Z:24586:cc-oci-runtime:critical:failed to read proxy socket fd
```

**Comment by jcvenegas** [comment] 2017-01-25 21:55
@chavafg  same here with 1.13, discarded the issue docker bug

**Comment by sameo** [comment] 2017-01-26 09:07
@jcvenegas Can you also reproduce it with 1.12.1 ?

**Comment by jcvenegas** [comment] 2017-01-26 20:37
@sameo yes, the error comes from hyperstart when tries to setup the network, seems that the device is not ready some times ... working in a fix

**Comment by devimc** [comment] 2017-02-17 18:56
Fixed in https://github.com/clearcontainers/hyperstart/pull/4

**Closed by devimc** 2017-02-17 18:56 UTC
Labels: domain:runtime
