### ISSUE TITLE
cc-proxy fails if /var/run/cc-oci-runtime is missing

### ISSUE THREAD

**Issue by sameo** [01org/cc-oci-runtime#459] opened 2016-11-24 18:32 UTC
After a fresh reboot, cc-oci-runtime never started and I get the following error:

```
sudo -E ./cc-proxy -v 4 --alsologtostderr
init: couldn't create AF_UNIX socket: listen unix /var/run/cc-oci-runtime/proxy.sock: bind: no such file or directory
```

I guess cc-proxy should create /var/run/cc-oci-runtime/ if it's not present.

**Comment by jodh-intel** [comment] 2016-11-25 11:12
This could be fixed by adding a `RuntimeDirectory=` to `proxy/cc-proxy.service.in`.

**Comment by dlespiau** [comment] 2016-11-25 11:31
Not quite :) systemd creates the directory for us already in the socket activation case (IIRC). The problem is when started the proxy from the command line and this directory doesn't exists. I'll have a patch in a few minutes.

**Comment by jodh-intel** [comment] 2016-11-25 11:44
ah, right - I always run it manually :)

**Closed** 2016-11-30 11:11 UTC
Labels: domain:proxy
